### ISSUE TITLE
include in more specific schematron files is ignored

### ISSUE THREAD

**Issue by mkraetke** [transpect/htmlreports#2]
When I insert an include in a more specific level of the cascade, the contents of the included schematron file are ignored. Even the most common rules have always more precedence than the included schematron files of the more specific schematron. This odd behaviour was introduced with commit db73aa1ca87f41800e8979727bf6b28cb68c23fb
@pglatza

**Comment by pglatza** [comment]
Thanks for your feedback.
I've fixed this issue in https://github.com/transpect/htmlreports/commit/7b0fe057460c566e3981e614b99e200d9ef6104c
